import type { MarketplaceListing } from "./types.js";

const PERBUG = {
  code: "PERBUG",
  symbol: "₱B",
  decimals: 2,
  displayName: "Perbug Shards",
  settlementRail: "offchain_game_balance",
} as const;

export function seedMarketplaceListings(): MarketplaceListing[] {
  return [
    {
      listingId: "mk_char_ashen_warden",
      assetReference: { assetId: "char_ashen_warden", assetType: "character", sourceModule: "squad", sourceRecordId: "squad_112" },
      assetName: "Ashen Warden",
      assetType: "character",
      rarity: "legendary",
      status: "active",
      seller: { sellerId: "player_nero", handle: "NeroMapwright", tier: "founder", reputationScore: 97 },
      price: { amount: "1800.00", atomicAmount: "180000", currency: PERBUG },
      createdAt: "2026-03-20T13:30:00.000Z",
      metadata: {
        imageUrl: "/perbug.svg",
        summary: "Frontline guardian tuned for siege-node defense.",
        level: 22,
        powerScore: 1180,
        roleClass: "Bulwark Vanguard",
      },
      provenance: { originLabel: "Founder Season Forge", tags: ["earned", "premium"], acquiredAt: "2026-02-01T10:00:00.000Z" },
      tradeEligibility: { listable: true, buyable: true, reasonCodes: [] },
      featuredRank: 1,
    },
    {
      listingId: "mk_relic_aurora_core",
      assetReference: { assetId: "relic_aurora_core", assetType: "relic", sourceModule: "relic_vault", sourceRecordId: "relic_slot_3" },
      assetName: "Aurora Core",
      assetType: "relic",
      rarity: "epic",
      status: "active",
      seller: { sellerId: "player_kite", handle: "KiteofRidges", tier: "adventurer", reputationScore: 88 },
      price: { amount: "640.00", atomicAmount: "64000", currency: PERBUG },
      createdAt: "2026-03-24T18:45:00.000Z",
      expiresAt: "2026-04-02T18:45:00.000Z",
      metadata: {
        imageUrl: "/perbug1.svg",
        summary: "Amplifies storm damage after node capture.",
        relicSlot: "Heart",
        relicType: "Elemental Core",
      },
      provenance: { originLabel: "Crafted at Windglass Forge", tags: ["crafted"], acquiredAt: "2026-03-18T07:05:00.000Z" },
      tradeEligibility: { listable: true, buyable: true, reasonCodes: [] },
      featuredRank: 2,
    },
    {
      listingId: "mk_item_star_compass",
      assetReference: { assetId: "item_star_compass", assetType: "item", sourceModule: "inventory", sourceRecordId: "inv_447" },
      assetName: "Star Compass",
      assetType: "item",
      rarity: "rare",
      status: "active",
      seller: { sellerId: "player_luna", handle: "LunaHarbor", tier: "guild", reputationScore: 90 },
      price: { amount: "210.00", atomicAmount: "21000", currency: PERBUG },
      createdAt: "2026-03-27T01:10:00.000Z",
      metadata: {
        imageUrl: "/logo.svg",
        summary: "Expedition utility that reveals hidden supply routes.",
        itemType: "Utility",
      },
      provenance: { originLabel: "Abyssal Expedition Drop", tags: ["event", "earned"], acquiredAt: "2026-03-25T15:11:00.000Z" },
      tradeEligibility: { listable: true, buyable: true, reasonCodes: [] },
    },
    {
      listingId: "mk_map_lumin_keep",
      assetReference: { assetId: "map_lumin_keep", assetType: "map_asset", sourceModule: "world_map", sourceRecordId: "node_7A" },
      assetName: "Lumin Keep Banner Rights",
      assetType: "map_asset",
      rarity: "mythic",
      status: "active",
      seller: { sellerId: "player_iris", handle: "IrisPathmaker", tier: "founder", reputationScore: 99 },
      price: { amount: "3200.00", atomicAmount: "320000", currency: PERBUG },
      createdAt: "2026-03-26T20:00:00.000Z",
      metadata: {
        imageUrl: "/social-card.svg",
        summary: "Guild prestige marker tied to node taxation rights.",
        mapLink: {
          nodeId: "node_7A",
          regionId: "emberfront",
          regionName: "Emberfront Expanse",
          landmarkName: "Lumin Keep",
          coordinateHint: { x: 73, y: 41 },
        },
      },
      provenance: { originLabel: "World Event Sovereignty Reward", tags: ["map_linked", "event", "premium"], acquiredAt: "2026-03-10T21:40:00.000Z" },
      tradeEligibility: { listable: true, buyable: true, reasonCodes: [] },
      featuredRank: 0,
    },
    {
      listingId: "mk_cosmetic_mosscloak",
      assetReference: { assetId: "cos_mosscloak", assetType: "cosmetic", sourceModule: "collectibles", sourceRecordId: "skin_12" },
      assetName: "Mosscloak of Old Vale",
      assetType: "cosmetic",
      rarity: "epic",
      status: "reserved",
      seller: { sellerId: "player_sora", handle: "SoraBloom", tier: "adventurer", reputationScore: 84 },
      price: { amount: "470.00", atomicAmount: "47000", currency: PERBUG },
      createdAt: "2026-03-21T02:00:00.000Z",
      metadata: {
        imageUrl: "/favicon.svg",
        summary: "Animated cloak skin from the Old Vale rites.",
      },
      provenance: { originLabel: "Premium Track Reward", tags: ["premium"], acquiredAt: "2026-03-01T10:00:00.000Z" },
      tradeEligibility: { listable: true, buyable: false, reasonCodes: ["listing_reserved"] },
    }
  ];
}
