import { EntitlementValueType, type EntitlementDefinition } from "./types.js";

export const ENTITLEMENT_DEFINITIONS: EntitlementDefinition[] = [
  { key: "ads_enabled", valueType: EntitlementValueType.BOOLEAN, description: "Show ads", defaultValue: true },
  { key: "advanced_search", valueType: EntitlementValueType.BOOLEAN, description: "Advanced search", defaultValue: false },
  { key: "ai_recommendations", valueType: EntitlementValueType.BOOLEAN, description: "AI recommendations", defaultValue: false },
  { key: "ai_itinerary_generation", valueType: EntitlementValueType.BOOLEAN, description: "AI itinerary generation", defaultValue: false },
  { key: "priority_support", valueType: EntitlementValueType.BOOLEAN, description: "Priority support", defaultValue: false },
  { key: "max_saved_places", valueType: EntitlementValueType.INTEGER, description: "Saved places", defaultValue: 20 },
  { key: "max_custom_lists", valueType: EntitlementValueType.INTEGER, description: "Custom lists", defaultValue: 2 },
  { key: "max_places_per_list", valueType: EntitlementValueType.INTEGER, description: "Places per list", defaultValue: 20 },
  { key: "max_text_reviews_per_month", valueType: EntitlementValueType.INTEGER, description: "Text reviews / month", defaultValue: 10 },
  { key: "max_photo_reviews_per_month", valueType: EntitlementValueType.INTEGER, description: "Photo reviews / month", defaultValue: 4 },
  { key: "max_video_reviews_per_month", valueType: EntitlementValueType.INTEGER, description: "Video reviews / month", defaultValue: 0 },
  { key: "max_photo_uploads_per_review", valueType: EntitlementValueType.INTEGER, description: "Photos / review", defaultValue: 1 },
  { key: "max_video_duration_seconds", valueType: EntitlementValueType.INTEGER, description: "Video duration", defaultValue: 0 },
  { key: "max_places_claimed", valueType: EntitlementValueType.INTEGER, description: "Claimed places", defaultValue: 0 },
  { key: "max_business_locations", valueType: EntitlementValueType.INTEGER, description: "Business locations", defaultValue: 1 },
  { key: "max_creator_guides", valueType: EntitlementValueType.INTEGER, description: "Creator guides", defaultValue: 0 },
  { key: "max_featured_posts", valueType: EntitlementValueType.INTEGER, description: "Featured posts", defaultValue: 0 },
  { key: "max_collaborations_per_month", valueType: EntitlementValueType.INTEGER, description: "Collaborations / month", defaultValue: 0 },
  { key: "creator_profile_enabled", valueType: EntitlementValueType.BOOLEAN, description: "Creator profile", defaultValue: false },
  { key: "creator_analytics", valueType: EntitlementValueType.BOOLEAN, description: "Creator analytics", defaultValue: false },
  { key: "creator_monetization_tools", valueType: EntitlementValueType.BOOLEAN, description: "Creator monetization", defaultValue: false },
  { key: "creator_verified_eligibility", valueType: EntitlementValueType.BOOLEAN, description: "Creator verification", defaultValue: false },
  { key: "premium_creator_badge", valueType: EntitlementValueType.BOOLEAN, description: "Premium creator badge", defaultValue: false },
  { key: "business_claiming_enabled", valueType: EntitlementValueType.BOOLEAN, description: "Business claiming", defaultValue: false },
  { key: "business_analytics", valueType: EntitlementValueType.BOOLEAN, description: "Business analytics", defaultValue: false },
  { key: "business_reply_to_reviews", valueType: EntitlementValueType.BOOLEAN, description: "Reply to reviews", defaultValue: false },
  { key: "business_promotions", valueType: EntitlementValueType.BOOLEAN, description: "Business promotions", defaultValue: false },
  { key: "business_team_members", valueType: EntitlementValueType.INTEGER, description: "Business team members", defaultValue: 1 },
  { key: "can_access_beta_features", valueType: EntitlementValueType.BOOLEAN, description: "Beta features", defaultValue: false },
  { key: "can_purchase_promotions", valueType: EntitlementValueType.BOOLEAN, description: "Purchase promotions", defaultValue: false },
  { key: "can_be_featured", valueType: EntitlementValueType.BOOLEAN, description: "Can be featured", defaultValue: false },
  { key: "can_receive_priority_ranking", valueType: EntitlementValueType.BOOLEAN, description: "Priority ranking", defaultValue: false },
  { key: "creator_tips_enabled", valueType: EntitlementValueType.BOOLEAN, description: "Creator tips enabled", defaultValue: false },
  { key: "creator_premium_content_enabled", valueType: EntitlementValueType.BOOLEAN, description: "Creator premium content", defaultValue: false },
  { key: "creator_featured_eligibility", valueType: EntitlementValueType.BOOLEAN, description: "Creator featured eligibility", defaultValue: false },
  { key: "creator_extended_upload_limits", valueType: EntitlementValueType.BOOLEAN, description: "Creator extended upload limits", defaultValue: false },
  { key: "creator_premium_analytics", valueType: EntitlementValueType.BOOLEAN, description: "Creator premium analytics", defaultValue: false },
  { key: "creator_membership_hooks_enabled", valueType: EntitlementValueType.BOOLEAN, description: "Creator membership foundations", defaultValue: false },
  { key: "creator_video_extended_limits", valueType: EntitlementValueType.BOOLEAN, description: "Creator video extended limits", defaultValue: false },
  { key: "creator_priority_review_support", valueType: EntitlementValueType.BOOLEAN, description: "Creator priority review support", defaultValue: false },
];
