server {
  listen 80;
  server_name geo.perbug.com;
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl http2;
  server_name geo.perbug.com;

  ssl_certificate /etc/letsencrypt/live/geo.perbug.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/geo.perbug.com/privkey.pem;

  access_log /var/log/nginx/geo.access.log;
  error_log /var/log/nginx/geo.error.log;

  location / {
    proxy_pass http://127.0.0.1:8081;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_connect_timeout 3s;
    proxy_send_timeout 10s;
    proxy_read_timeout 10s;
  }
}
